"""GitHub side-effects for the Patchwork node: drafting and (optionally) opening the PR.

The PR is opened only after the Validator approves, and only when a token is
available — otherwise the pipeline returns a fully-drafted (but unopened) PR, so
the whole flow still runs offline.
"""

from __future__ import annotations

import logging

from .schemas import GitHubIssue, Patch, PullRequest, ValidationResult

logger = logging.getLogger("nexus.github")

def _coverage_emoji(score: float) -> str:
    return "🟢" if score >= 0.8 else "🟡" if score >= 0.6 else "🔴"


def draft_pull_request(
    issue: GitHubIssue, patch: Patch, validation: ValidationResult
) -> PullRequest:
    """Compose the PR title/body/branch — pure, no network."""
    emoji = _coverage_emoji(validation.coverage_score)  # headline = Validator's verdict
    body = (
        f"## Regression test for #{issue.issue_number}\n\n"
        f"Generated by the **Nexus** pipeline (Bug Analyzer → Patchwork → Validator).\n\n"
        f"### What this test does\n"
        f"`{patch.test_file_path}` — {patch.summary}\n\n"
        f"It is designed to **fail while the bug exists** and **pass once it's fixed**.\n\n"
        f"### Validator verdict\n"
        f"{emoji} coverage **{validation.coverage_score:.0%}** — {validation.rationale}\n\n"
        f"> Patch confidence: {patch.confidence.value.upper()} · framework: {patch.framework}\n"
    )
    return PullRequest(
        branch=f"nexus/issue-{issue.issue_number}",
        title=f"[Nexus] Regression test for #{issue.issue_number}: {issue.title}",
        body=body,
        url="",
        opened=False,
    )


def open_pull_request(
    issue: GitHubIssue,
    patch: Patch,
    validation: ValidationResult,
    *,
    token: str | None,
) -> PullRequest:
    """Draft the PR, and actually open it via the GitHub API when a token is present."""
    pr = draft_pull_request(issue, patch, validation)
    if not token:
        logger.info("No GITHUB_TOKEN set — leaving PR for #%s as a draft.", issue.issue_number)
        return pr

    try:
        from github import Auth, Github  # PyGithub, imported lazily

        repo = Github(auth=Auth.Token(token)).get_repo(issue.repo_full_name)
        base = repo.default_branch
        base_sha = repo.get_branch(base).commit.sha
        repo.create_git_ref(ref=f"refs/heads/{pr.branch}", sha=base_sha)
        repo.create_file(
            path=patch.test_file_path,
            message=f"test: regression test for #{issue.issue_number}",
            content=patch.test_code,
            branch=pr.branch,
        )
        created = repo.create_pull(title=pr.title, body=pr.body, head=pr.branch, base=base)
        pr.url, pr.opened = created.html_url, True
        logger.info("Opened PR: %s", pr.url)
    except Exception as exc:  # network/permission failures shouldn't crash the pipeline
        logger.warning("Could not open PR (%s); returning the draft.", exc)
    return pr
